image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - ps: $env:build_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version 
  - ps: $env:build_description = (Get-Content -Raw -Path package.json | ConvertFrom-Json).description
  - ps: Update-AppveyorBuild -Version "$env:build_version.$env:APPVEYOR_BUILD_NUMBER"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(build_version)
  package_version: $(build_version)

before_build:
- cmd: dotnet restore

build:
  project: package.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: '**\Unity.*.nupkg'
  name: 'Unity'

deploy:
- provider: GitHub
  force_update: true
  description: $(build_description)
  tag: $(appveyor_repo_tag_name)
  release: $(appveyor_repo_tag_name)
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  auth_token:
    secure: 0RltkfAMN35pApf7xYqjwy1EgsVeniSYPv35Qb9ntHY1b4SC51QYLXVVfklvw09j
  on:
    appveyor_repo_tag: true        # deploy on tag push only  
- provider: NuGet
  api_key:
    secure: Q/HUObjarHxWF0NlnHBDY5uMQHM4ESyKfFCYdbRVfsNrWUFozADu6FMvh44gEmFk
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true        # deploy on tag push only 
